name: Feature request
description: Suggest an improvement or new capability
title: "feature: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion. Please keep requests focused and avoid sharing secrets.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: "What problem are you trying to solve?"
      placeholder: "I want to..."
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: "What would you like to see implemented?"
      placeholder: "A possible solution is..."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: "Other approaches considered..."
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      placeholder: "Links, references, or constraints..."
    validations:
      required: false
